spring.application.name=Campus GIG

# ==============================
# SERVER PORT
# ==============================
server.port=8080

# ==============================
# DATABASE CONFIGURATION
# ==============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}

# ==============================
# JPA / HIBERNATE CONFIGURATION
# ==============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ==============================
# OPTIONAL (Recommended)
# ==============================
spring.jpa.open-in-view=false

#===============================
# Redis Configuration
#===============================
spring.data.redis.host=localhost
spring.data.redis.port=6379
#spring.data.redis.timeout=60000