package org.riteshingle.campusgig.Enum;

public enum JobCategory {
    WEB_DEVELOPMENT,
    APP_DEVELOPMENT,
    UI_UX_DESIGN,
    GRAPHIC_DESIGN,
    CONTENT_WRITING,
    VIDEO_EDITING,
    DIGITAL_MARKETING,
    SEO,
    DATA_ENTRY,
    DATA_ANALYSIS,
    SOFTWARE_TESTING,
    DATABASE_DEVELOPMENT,
    JAVA_DEVELOPMENT,
    PYTHON_DEVELOPMENT,
    REACT_DEVELOPMENT,
    WORDPRESS_DEVELOPMENT,
    TUTORING,
    TRANSLATION,
    FRONTEND_DEVELOPMENT,
    OTHER
}
